
package com.pukhova.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AuthorisationImplService", targetNamespace = "http://ws.pukhova.com/", wsdlLocation = "http://localhost:1234/ws/auth?wsdl")
public class AuthorisationImplService
    extends Service
{

    private final static URL AUTHORISATIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTHORISATIONIMPLSERVICE_EXCEPTION;
    private final static QName AUTHORISATIONIMPLSERVICE_QNAME = new QName("http://ws.pukhova.com/", "AuthorisationImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/ws/auth?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHORISATIONIMPLSERVICE_WSDL_LOCATION = url;
        AUTHORISATIONIMPLSERVICE_EXCEPTION = e;
    }

    public AuthorisationImplService() {
        super(__getWsdlLocation(), AUTHORISATIONIMPLSERVICE_QNAME);
    }

    public AuthorisationImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHORISATIONIMPLSERVICE_QNAME, features);
    }

    public AuthorisationImplService(URL wsdlLocation) {
        super(wsdlLocation, AUTHORISATIONIMPLSERVICE_QNAME);
    }

    public AuthorisationImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHORISATIONIMPLSERVICE_QNAME, features);
    }

    public AuthorisationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthorisationImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Authorisation
     */
    @WebEndpoint(name = "AuthorisationImplPort")
    public Authorisation getAuthorisationImplPort() {
        return super.getPort(new QName("http://ws.pukhova.com/", "AuthorisationImplPort"), Authorisation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Authorisation
     */
    @WebEndpoint(name = "AuthorisationImplPort")
    public Authorisation getAuthorisationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.pukhova.com/", "AuthorisationImplPort"), Authorisation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHORISATIONIMPLSERVICE_EXCEPTION!= null) {
            throw AUTHORISATIONIMPLSERVICE_EXCEPTION;
        }
        return AUTHORISATIONIMPLSERVICE_WSDL_LOCATION;
    }

}
